### ISSUE TITLE
What's a Secret NFT? Link appears to do nothing

### ISSUE THREAD

**Issue by DanGar2** [SecretChainGirl-Foundation/stashh-QA#142]
The Link does not take you to anything identify what a secret NFT is.

**Comment by scarylooking** [comment]
This is expected - the "What's a Secret NFT?" link takes you back to the homepage. It could probably do with some separate content explaining what the benefits of a Secret NFT are

**Comment by lauraweindorf** [comment]
Yeah, I think it really does need some content for that because it's confusing for users ... they click that and see the top of  the Stashh home page with nothing talking about what a Secret NFT is. at that spot. Maybe that link could at least take the user down to the section that talks about why privacy matters for NFTs?

I really think this should be labeled as an issue as opposed to an enhancement @scarylooking.

**Comment by lauraweindorf** [comment]
I highly recommend that the link opens a new tab to this: https://scrt.network/about/secret-nfts

![image](https://user-images.githubusercontent.com/436905/142785481-e2d71fc8-52dc-43c5-8de6-4ce9eeb64cd4.png)


cc @scarylooking @LourencoMaltez

**Comment by DanGar2** [comment]
I think it would be good to link to this. I'm just thinking if we want this to be an NFT site for the masses to utilize there will be experienced and novice users. Will be good for the novice users to be able to identify what a Secret NFT is. Also I like that the link laura mentions has a segment on Traditional NFTs vs Secret NFTs.
